# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_todo_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
