# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0006_auto_20170417_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
